In [ ]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     |████████████████████████████████| 19.4 MB 644 kB/s
Collecting JPype1>=0.7.0
  Downloading JPype1-1.4.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (453 kB)
     |████████████████████████████████| 453 kB 73.4 MB/s
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.21.6)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.9.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (4.1.1)
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.4.0 konlpy-0.6.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/Shareddrives/솔룩스 데이텀/naver_book_책정보.csv")
df

                         0                                                  1
0     사랑하라 한번도 상처받지 않은 것처럼   시집 <그대가 곁에 있어도 나는 그대가 그립다> <외눈박이 물고기의 사랑>의 저자...
1                     마음사전  수만 가지의 빛깔을 지닌 ‘마음’에 관한 ‘사전’─희로애락애오욕 300낱말이 마음의...
2                입 속의 검은 잎  '문학과지성 시인선' 80권, 기형도 시집. 처음이자 마지막이 된 이 시집에서 기형...
3                   행복의 정복  활발한 사회활동을 펼친 20세기의 지성으로 유명한 러셀이 쓴 단 한 권의 행복론. ...
4                     백범일지  본격적인 원전비평으로 정본화에 완벽을 기한 『백범일지』 \n 일반적으로 역사적 문헌...
...                    ...                                                ...
3969                 토지 17  시인 쵸서의 작품을 분석한 책. 과학의 이론에 관계된 추상적인 세계가 아니라 실제 ...
3970                  토지 5                                                  X
3971                 토지 13                                                  X
3972                 마천루 1  자신만의 뚜렷한 문체, 일관된 삶과 예술적 사상을 바탕으로 145편의 작품을 남긴 ...
3973               고요한 돈 강                                                  X

[3974 rows x 2 columns]

In [ ]:
df = df[df['1'] != 'X']
df = df.reset_index()
df

,index,0,1
0,0,사랑하라 한번도 상처받지 않은 것처럼,시집 <그대가 곁에 있어도 나는 그대가 그립다> <외눈박이 물고기의 사랑>의 저자...
1,1,마음사전,수만 가지의 빛깔을 지닌 ‘마음’에 관한 ‘사전’─희로애락애오욕 300낱말이 마음의...
2,2,입 속의 검은 잎,"'문학과지성 시인선' 80권, 기형도 시집. 처음이자 마지막이 된 이 시집에서 기형..."
3,3,행복의 정복,활발한 사회활동을 펼친 20세기의 지성으로 유명한 러셀이 쓴 단 한 권의 행복론. ...
4,4,백범일지,본격적인 원전비평으로 정본화에 완벽을 기한 『백범일지』 \n 일반적으로 역사적 문헌...
...,...,...,...
3923,3964,토지 11,"끊임없는 도전과 위협을 받고 있는 학자들을 통하여, 낯익고 일상적이며 당연한 현실의..."
3924,3965,토지 18,MBC 느낌표 추천도서 <톨스토이 단편선>에 이어 출간된 톨스토이 단편선 2권. 국...
3925,3968,토지 6,동국사영에 대해 연구한 책. '동국사영' 혹은 '동국고사사영'은 고려 후기의 이제현...
3926,3969,토지 17,시인 쵸서의 작품을 분석한 책. 과학의 이론에 관계된 추상적인 세계가 아니라 실제 ...
3927,3972,마천루 1,"자신만의 뚜렷한 문체, 일관된 삶과 예술적 사상을 바탕으로 145편의 작품을 남긴 ..."

In [ ]:
df = df.drop(['index'], axis=1)
df

                         0                                                  1
0     사랑하라 한번도 상처받지 않은 것처럼   시집 <그대가 곁에 있어도 나는 그대가 그립다> <외눈박이 물고기의 사랑>의 저자...
1                     마음사전  수만 가지의 빛깔을 지닌 ‘마음’에 관한 ‘사전’─희로애락애오욕 300낱말이 마음의...
2                입 속의 검은 잎  '문학과지성 시인선' 80권, 기형도 시집. 처음이자 마지막이 된 이 시집에서 기형...
3                   행복의 정복  활발한 사회활동을 펼친 20세기의 지성으로 유명한 러셀이 쓴 단 한 권의 행복론. ...
4                     백범일지  본격적인 원전비평으로 정본화에 완벽을 기한 『백범일지』 \n 일반적으로 역사적 문헌...
...                    ...                                                ...
3923                 토지 11  끊임없는 도전과 위협을 받고 있는 학자들을 통하여, 낯익고 일상적이며 당연한 현실의...
3924                 토지 18  MBC 느낌표 추천도서 <톨스토이 단편선>에 이어 출간된 톨스토이 단편선 2권. 국...
3925                  토지 6  동국사영에 대해 연구한 책. '동국사영' 혹은 '동국고사사영'은 고려 후기의 이제현...
3926                 토지 17  시인 쵸서의 작품을 분석한 책. 과학의 이론에 관계된 추상적인 세계가 아니라 실제 ...
3927                 마천루 1  자신만의 뚜렷한 문체, 일관된 삶과 예술적 사상을 바탕으로 145편의 작품을 남긴 ...

[3928 rows x 2 columns]

In [ ]:
# 경고문을 무시합니다.
import warnings
warnings.filterwarnings(action='ignore')

from konlpy.tag import Okt

okt = Okt()

In [ ]:
stem_pos_results=[]

#3974
for i in range(0,len(df['0']),10):
  list=[]
  list = okt.pos(df['1'][i], stem =True)
  stem_pos_results.append([df['0'][i],list])

print(stem_pos_results)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
print(len(stem_pos_results))

393

In [ ]:
stem_df = pd.DataFrame(stem_pos_results)
stem_df

                        0                                                  1
0    사랑하라 한번도 상처받지 않은 것처럼  [(<, Punctuation), (그대, Noun), (가, Josa), (곁, ...
1             달라이 라마의 행복론  [(14, Number), (대다, Verb), (달라이라마, Noun), (텐진,...
2                  즐거운 일기  [(이, Noun), (책, Noun), (은, Josa), (최승자, Noun),...
3             내 아버지로부터의 꿈  [(따뜻하다, Adjective), (휴머니즘, Noun), (,, Punctuat...
4                 위대한 패배자  [(세계, Noun), (는, Josa), (1등, Number), (만을, For...
..                    ...                                                ...
388            현대사회와 구비문학  [(<, Punctuation), (퇴, Noun), (계집, Noun), (>, ...
389                퇴계시 색인  [(<, Punctuation), (증보, Noun), (가곡원류, Noun), (...
390                  가곡원류  [(', Punctuation), (우리, Noun), (가, Josa), (읽다,...
391                   춘향전  [(1994년, Number), (집필, Noun), (완료, Noun), (되다,...
392                 토지 20  [(<, Punctuation), (김, Noun), (약국, Noun), (의, ...

[393 rows x 2 columns]

In [ ]:
print(stem_pos_results[0][1][0])

('<', 'Punctuation')

In [ ]:
result=[]
for i in range(len(stem_pos_results)):
  list=[]
  for j in range(len(stem_pos_results[i][1])):
    a,b = stem_pos_results[i][1][j]
    if b == 'Noun' or b == 'Adjective' or b == 'Verb':
      list.append(a)
      #result.append(list)
    else:
      continue
  result.append([stem_pos_results[i][0], list])

In [ ]:
print(len(result))

393

In [ ]:
result_df = pd.DataFrame(result)
result_df

                        0                                                  1
0    사랑하라 한번도 상처받지 않은 것처럼  [그대, 곁, 있다, 나, 그대, 그리다, 외눈박이, 물고기, 사랑, 의, 저자, ...
1             달라이 라마의 행복론  [대다, 달라이라마, 텐진, 가다, 그, 티벳, 망명정부, 법왕, 이, 아니다, 사...
2                  즐거운 일기  [이, 책, 최승자, 시인, 첫, 시집, 이후, 펴내다, 것, 더, 나아가다, 데,...
3             내 아버지로부터의 꿈  [따뜻하다, 휴머니즘, 빛나다, 지성, 부드럽다, 카리스마, 겸비, 미국, 최초, ...
4                 위대한 패배자  [세계, 기억, 무한, 경쟁, 시대, 살, 있다, 현대인, 누군가, 반드시, 이기다...
..                    ...                                                ...
388            현대사회와 구비문학  [퇴, 계집, 수록, 되어다, 있다, 시구, 시제, 및, 서문, 주석, 등, 모두,...
389                퇴계시 색인  [증보, 가곡원류, 를, 번역, 책, 누구, 읽다, 감상, 하다, 수, 있다, 주석...
390                  가곡원류  [우리, 읽다, 하다, 고전, 시리즈, 중, 하나로, 춘향전, 이, 추다, 간, 되...
391                   춘향전  [집필, 완료, 되다, 후, 독자, 많다, 사랑, 받다, 토지, 이후, 절판, 되어...
392                 토지 20  [김, 약국, 딸, 의, 작가, 박경리, 대하, 장편소설, 토지, 권, 부, 권, ...

[393 rows x 2 columns]

In [ ]:
result_df.to_csv("naverbook_konlpy.csv", encoding='utf-8-sig', index=False, header = False) 
from google.colab import files
files.download("naverbook_konlpy.csv")